services:
  db:
    image: postgres:15
    container_name: car_rental_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_rental
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: car_rental_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL_ALEMBIC: ${DATABASE_URL_ALEMBIC}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      TELEGRAM_BOT_CHAT_ID: ${TELEGRAM_BOT_CHAT_ID}
      TELEGRAM_BOT_API_TOKEN: ${TELEGRAM_BOT_API_TOKEN}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db

volumes:
  postgres_data: