"""reservation_entity_modification

Revision ID: 68acae8a754d
Revises: 179a964fab77
Create Date: 2026-02-06 15:38:38.246883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68acae8a754d'
down_revision: Union[str, None] = '179a964fab77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('status', sa.String(), nullable=True))
    op.add_column('reservations', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('reservations', sa.Column('total_days', sa.Integer(), nullable=True))
    op.add_column('reservations', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'created_at')
    op.drop_column('reservations', 'total_days')
    op.drop_column('reservations', 'price')
    op.drop_column('reservations', 'status')
    # ### end Alembic commands ###
