"""add_updated_at_column_to_reservation_entity

Revision ID: 8a689481024b
Revises: 68acae8a754d
Create Date: 2026-02-06 16:17:44.389727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a689481024b'
down_revision: Union[str, None] = '68acae8a754d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'updated_at')
    # ### end Alembic commands ###
