"""connecting review with reservation

Revision ID: dda7f13698fd
Revises: 885fe7a52974
Create Date: 2026-02-17 12:41:29.420009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda7f13698fd'
down_revision: Union[str, None] = '885fe7a52974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reservation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'reservations', ['reservation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'reservation_id')
    # ### end Alembic commands ###
