"""add a flag for non existing user in reservation

Revision ID: e8401b07147d
Revises: f3595d9582c1
Create Date: 2026-02-17 13:35:07.027248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8401b07147d'
down_revision: Union[str, None] = 'f3595d9582c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('non_existing_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'non_existing_user')
    # ### end Alembic commands ###
