"""Update reservation model

Revision ID: f3595d9582c1
Revises: dda7f13698fd
Create Date: 2026-02-17 13:09:51.167628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3595d9582c1'
down_revision: Union[str, None] = 'dda7f13698fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('email', sa.String(), nullable=True))
    op.add_column('reservations', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('reservations', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'full_name')
    op.drop_column('reservations', 'phone_number')
    op.drop_column('reservations', 'email')
    # ### end Alembic commands ###
